const initialProducts = [
  {
    _id: 'prod_1',
    title: 'J&J Vintage Leather Biker Jacket',
    slug: 'jj-vintage-leather-biker-jacket',
    sku: 'JJV-JKT-1001',
    barcode: '890123456701',
    price: 350000,
    salePrice: 295000,
    category: 'Outerwear',
    parentCategory: 'Men',
    brand: 'J&J Vintage',
    stock: 15,
    lowStockThreshold: 3,
    description: 'Authentic handcrafted full-grain calfskin leather jacket with custom gold hardware and plush viscose lining.',
    specifications: [
      { key: 'Material', value: '100% Italian Calfskin' },
      { key: 'Hardware', value: '24K Gold-Plated Zippers' },
      { key: 'Fit', value: 'Vintage Tailored Silhouette' },
    ],
    colors: [
      { name: 'Matte Black', hex: '#0B0B0B' },
      { name: 'Cognac Gold', hex: '#9E7B3B' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.9,
    numReviews: 28,
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    isFlashSale: true,
    discountPercentage: 15,
    tags: ['vintage', 'biker', 'leather', 'gold'],
  },
  {
    _id: 'prod_2',
    title: 'J&J Vintage Silk Evening Gown',
    slug: 'jj-vintage-silk-evening-gown',
    sku: 'JJV-GWN-2002',
    barcode: '890123456702',
    price: 420000,
    salePrice: 380000,
    category: 'Dresses',
    parentCategory: 'Women',
    brand: 'J&J Vintage',
    stock: 8,
    lowStockThreshold: 2,
    description: 'Exquisite floor-length Mulberry silk gown with dramatic back draping and subtle gold embroidery along the neckline.',
    specifications: [
      { key: 'Fabric', value: '100% Mulberry Silk' },
      { key: 'Closure', value: 'Concealed Side Zipper' },
    ],
    colors: [
      { name: 'Emerald Gold', hex: '#123524' },
      { name: 'Midnight Onyx', hex: '#111111' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 5.0,
    numReviews: 42,
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    isFlashSale: false,
    discountPercentage: 10,
    tags: ['silk', 'gown', 'vintage', 'women'],
  },
  {
    _id: 'prod_3',
    title: 'J&J Vintage Gold Runner Sneakers',
    slug: 'jj-vintage-gold-runner-sneakers',
    sku: 'JJV-RUN-3003',
    barcode: '890123456703',
    price: 185000,
    salePrice: 160000,
    category: 'Sneakers',
    parentCategory: 'Shoes',
    brand: 'J&J Vintage',
    stock: 22,
    lowStockThreshold: 5,
    description: 'High-performance street luxury sneakers featuring breathable mesh, gold foil panelling, and shock-absorbing rubber outsole.',
    specifications: [
      { key: 'Upper', value: 'PrimeKnit & Leather' },
      { key: 'Sole', value: 'Cloud-Bounce Rubber' },
    ],
    colors: [
      { name: 'Gold Onyx', hex: '#D4AF37' },
      { name: 'Pure White', hex: '#FFFFFF' },
    ],
    sizes: ['40', '41', '42', '43', '44', '45'],
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.8,
    numReviews: 64,
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    isFlashSale: true,
    discountPercentage: 14,
    tags: ['sneakers', 'gold', 'shoes', 'vintage'],
  },
  {
    _id: 'prod_4',
    title: 'J&J Vintage Chronograph Watch',
    slug: 'jj-vintage-chronograph-watch',
    sku: 'JJV-WTC-4004',
    barcode: '890123456704',
    price: 850000,
    salePrice: 790000,
    category: 'Jewelry',
    parentCategory: 'Accessories',
    brand: 'J&J Vintage',
    stock: 5,
    lowStockThreshold: 1,
    description: 'Automatic chronometer featuring scratch-resistant sapphire crystal glass, 18K gold casing, and crocodile embossed leather strap.',
    specifications: [
      { key: 'Movement', value: 'Swiss Automatic 3135' },
      { key: 'Case Diameter', value: '41mm' },
    ],
    colors: [{ name: 'Royal Gold', hex: '#C5A059' }],
    sizes: ['One Size'],
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 5.0,
    numReviews: 19,
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    isFlashSale: false,
    discountPercentage: 7,
    tags: ['watch', 'luxury', 'gold', 'vintage'],
  },
  {
    _id: 'prod_5',
    title: 'J&J Vintage Monogram Tote Bag',
    slug: 'jj-vintage-monogram-tote-bag',
    sku: 'JJV-TOT-5005',
    barcode: '890123456705',
    price: 270000,
    salePrice: 0,
    category: 'Bags',
    parentCategory: 'Bags',
    brand: 'J&J Vintage',
    stock: 14,
    lowStockThreshold: 4,
    description: 'Spacious tote bag with structured leather handles, gold clasp, and removable internal zipped pouch.',
    specifications: [
      { key: 'Dimensions', value: '40cm x 30cm x 15cm' },
      { key: 'Material', value: 'Canvas & Calfskin' },
    ],
    colors: [
      { name: 'Onyx Black', hex: '#000000' },
      { name: 'Camel Tan', hex: '#C19A6B' },
    ],
    sizes: ['Medium', 'Large'],
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.7,
    numReviews: 31,
    isFeatured: true,
    isNewArrival: false,
    isTrending: true,
    isFlashSale: false,
    discountPercentage: 0,
    tags: ['bag', 'tote', 'vintage', 'monogram'],
  },
  {
    _id: 'prod_6',
    title: 'J&J Vintage Cashmere Hoodie',
    slug: 'jj-vintage-cashmere-hoodie',
    sku: 'JJV-HUD-6006',
    barcode: '890123456706',
    price: 145000,
    salePrice: 120000,
    category: 'Sweatshirts',
    parentCategory: 'Men',
    brand: 'J&J Vintage',
    stock: 30,
    lowStockThreshold: 5,
    description: 'Ultra-soft cashmere blend hoodie designed with dropped shoulders and high-density gold chest emblem.',
    specifications: [
      { key: 'Composition', value: '70% Cashmere, 30% Cotton' },
    ],
    colors: [
      { name: 'Jet Black', hex: '#0A0A0A' },
      { name: 'Cream Sand', hex: '#F5F5DC' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.9,
    numReviews: 53,
    isFeatured: false,
    isNewArrival: true,
    isTrending: true,
    isFlashSale: true,
    discountPercentage: 17,
    tags: ['cashmere', 'hoodie', 'vintage'],
  },
];

module.exports = { initialProducts };
